from datetime import date
from typing import Any, Protocol
from uuid import UUID


class FinanceRepository(Protocol):
    async def upsert_investment(self, values: dict[str, Any]) -> None: ...
    async def ensure_user(self, user_id: UUID) -> None: ...
    async def list_connections(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def upsert_connection(
        self, user_id: UUID, item_id: str, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def update_connection(self, connection_id: str, values: dict[str, Any]) -> None: ...
    async def start_sync_run(self, user_id: UUID, sync_id: UUID) -> bool: ...
    async def finish_sync_run(self, sync_id: UUID, values: dict[str, Any]) -> None: ...
    async def get_sync_run(self, user_id: UUID, sync_id: UUID) -> dict[str, Any] | None: ...
    async def upsert_financial_account(
        self, values: dict[str, Any]
    ) -> tuple[dict[str, Any], bool]: ...
    async def upsert_credit_card(self, values: dict[str, Any]) -> tuple[dict[str, Any], bool]: ...
    async def upsert_transaction_batch(self, records: list[dict[str, Any]]) -> dict[str, int]: ...
    async def reconciliation_candidates(
        self, user_id: UUID, start: date
    ) -> list[dict[str, Any]]: ...
    async def update_reconciled_transactions(self, records: list[dict[str, Any]]) -> None: ...
    async def account_types(self, user_id: UUID) -> dict[str, str]: ...
    async def category_id(self, user_id: UUID, category_type: str, name: str) -> str: ...
    async def delete_connection(self, user_id: UUID, item_id: str) -> bool: ...
    async def register_webhook_event(self, values: dict[str, Any]) -> bool: ...
    async def update_webhook_event(self, event_id: str, values: dict[str, Any]) -> None: ...
